import Head from 'next/head'
import NewspaperIcon from '@mui/icons-material/Newspaper';

export default function HeadSEO() {
    return (
        <Head>
            <title>Newspaper</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}
